name: Run Tests
on:
  push:
    branches:
    - main
jobs:
  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: run test suites
      shell: bash
      run: ./.github/scripts/run-tests.sh
    - name: collect test results
      uses: dorny/test-reporter@v2
      with:
        name: Exercise Tests
        path: "exercises/**/junit-report.xml"
        reporter: jest-junit
      if: always()
